# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\x05\x61udio\"l\n\nAudioChunk\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06seq_id\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x10\n\x08wav_data\x18\x05 \x01(\x0c\"&\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06seq_id\x18\x02 \x01(\t2;\n\rAudioIngestor\x12*\n\tSendAudio\x12\x11.audio.AudioChunk\x1a\n.audio.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=22
  _globals['_AUDIOCHUNK']._serialized_end=130
  _globals['_ACK']._serialized_start=132
  _globals['_ACK']._serialized_end=170
  _globals['_AUDIOINGESTOR']._serialized_start=172
  _globals['_AUDIOINGESTOR']._serialized_end=231
# @@protoc_insertion_point(module_scope)
